[client]
showErrorDetails = "none"
toolbarMode = "minimal"

[server]
maxUploadSize = 100

[browser]
gatherUsageStats = false

[theme]
base = "dark"
font = "sans serif"
primaryColor = "#53C9BE"
chartCategoricalColors = [
    "#FA8991",
    "#F4A26D",
    "#E8C76A",
    "#81CAA3",
    "#53C9BE",
    "#97B6D5",
]
showSidebarBorder = true

[theme.dark]
primaryColor = "#53C9BE"
backgroundColor = "#0C121C"
secondaryBackgroundColor = "#141F2C"
textColor = "#E5ECF4"
redColor = "#FA8991"
orangeColor = "#F4A26D"
yellowColor = "#E8C76A"
greenColor = "#81CAA3"
blueColor = "#97B6D5"

[theme.dark.sidebar]
primaryColor = "#53C9BE"
backgroundColor = "#101923"
secondaryBackgroundColor = "#182534"
textColor = "#E5ECF4"

[theme.light]
primaryColor = "#0E706D"
backgroundColor = "#F6F8FB"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1D2B3D"
redColor = "#AE2B3B"
orangeColor = "#A04413"
yellowColor = "#785A0D"
greenColor = "#246843"
blueColor = "#3A628A"

[theme.light.sidebar]
primaryColor = "#0E706D"
backgroundColor = "#EDF1F6"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1D2B3D"
